CREATE TABLE "agent_messages" (
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL,
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "agent_messages_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"agent_thread_id" bigint NOT NULL,
	"role" text NOT NULL,
	"content" text NOT NULL,
	"metadata" jsonb
);
--> statement-breakpoint
CREATE TABLE "agent_threads" (
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL,
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "agent_threads_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"mailbox_id" bigint NOT NULL,
	"slack_channel" text NOT NULL,
	"thread_ts" text NOT NULL
);
--> statement-breakpoint
CREATE INDEX "agent_messages_agent_thread_id_idx" ON "agent_messages" USING btree ("agent_thread_id");--> statement-breakpoint
CREATE INDEX "agent_threads_mailbox_id_idx" ON "agent_threads" USING btree ("mailbox_id");--> statement-breakpoint
CREATE INDEX "agent_threads_slack_channel_thread_ts_idx" ON "agent_threads" USING btree ("slack_channel","thread_ts");