CREATE TABLE IF NOT EXISTS "tools" (
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL,
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "tools_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"description" text NOT NULL,
	"mailbox_id" bigint NOT NULL,
	"slug" text NOT NULL,
	"request_method" text NOT NULL,
	"url" text NOT NULL,
	"headers" jsonb DEFAULT '{}',
	"parameters" jsonb DEFAULT '[]',
	"authentication_method" text DEFAULT 'none' NOT NULL,
	"authentication_token" "bytea"
);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "tools_mailbox_id_idx" ON "tools" USING btree ("mailbox_id");--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "unique_slug_idx" ON "tools" USING btree ("slug");
