CREATE TABLE IF NOT EXISTS "conversation_events" (
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL,
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "conversation_events_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"conversation_id" bigint NOT NULL,
	"changes" jsonb NOT NULL,
	"by_clerk_user_id" text,
	"reason" text
);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "conversation_events_conversation_id_idx" ON "conversation_events" USING btree ("conversation_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "conversation_events_by_clerk_user_id_idx" ON "conversation_events" USING btree ("by_clerk_user_id");