CREATE TYPE "public"."guide_session_event_type" AS ENUM('session_started', 'step_added', 'step_completed', 'step_updated', 'action_performed', 'completed', 'abandoned', 'paused');--> statement-breakpoint
CREATE TYPE "public"."guide_session_status" AS ENUM('started', 'planning', 'active', 'completed', 'abandoned', 'paused');--> statement-breakpoint
CREATE TABLE "guide_session_events" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "guide_session_events_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"guide_session_id" bigint NOT NULL,
	"type" "guide_session_event_type" NOT NULL,
	"data" jsonb DEFAULT '{}'::jsonb,
	"timestamp" timestamp with time zone DEFAULT now() NOT NULL,
	"mailbox_id" bigint NOT NULL
);
--> statement-breakpoint
CREATE TABLE "guide_session_replays" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "guide_session_replays_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"guide_session_id" bigint NOT NULL,
	"type" text NOT NULL,
	"data" text NOT NULL,
	"timestamp" timestamp with time zone DEFAULT now() NOT NULL,
	"metadata" jsonb DEFAULT '{}'::jsonb,
	"mailbox_id" bigint NOT NULL
);
--> statement-breakpoint
CREATE TABLE "guide_sessions" (
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL,
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "guide_sessions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"uuid" uuid DEFAULT gen_random_uuid() NOT NULL,
	"platform_customer_id" bigint NOT NULL,
	"conversation_id" bigint,
	"status" "guide_session_status" DEFAULT 'started' NOT NULL,
	"title" text NOT NULL,
	"instructions" text,
	"steps" jsonb DEFAULT '[]'::jsonb,
	"metadata" jsonb DEFAULT '{}'::jsonb,
	"mailbox_id" bigint NOT NULL,
	CONSTRAINT "guide_sessions_uuid_unique" UNIQUE("uuid")
);
--> statement-breakpoint
CREATE INDEX "guide_session_events_timestamp_idx" ON "guide_session_events" USING btree ("timestamp");--> statement-breakpoint
CREATE INDEX "guide_session_events_guide_session_id_idx" ON "guide_session_events" USING btree ("guide_session_id");--> statement-breakpoint
CREATE INDEX "guide_session_events_type_idx" ON "guide_session_events" USING btree ("type");--> statement-breakpoint
CREATE INDEX "guide_session_events_mailbox_id_idx" ON "guide_session_events" USING btree ("mailbox_id");--> statement-breakpoint
CREATE INDEX "guide_session_replays_guide_session_id_idx" ON "guide_session_replays" USING btree ("guide_session_id");--> statement-breakpoint
CREATE INDEX "guide_session_replays_timestamp_idx" ON "guide_session_replays" USING btree ("timestamp");--> statement-breakpoint
CREATE INDEX "guide_session_replays_mailbox_id_idx" ON "guide_session_replays" USING btree ("mailbox_id");--> statement-breakpoint
CREATE INDEX "guide_sessions_created_at_idx" ON "guide_sessions" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "guide_sessions_platform_customer_id_idx" ON "guide_sessions" USING btree ("platform_customer_id");--> statement-breakpoint
CREATE INDEX "guide_sessions_conversation_id_idx" ON "guide_sessions" USING btree ("conversation_id");--> statement-breakpoint
CREATE INDEX "guide_sessions_mailbox_id_idx" ON "guide_sessions" USING btree ("mailbox_id");--> statement-breakpoint
CREATE INDEX "guide_sessions_status_idx" ON "guide_sessions" USING btree ("status");