-- Unlogged for faster performance at the cost of durability
CREATE UNLOGGED TABLE "cache" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "cache_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"key" text NOT NULL,
	"value" jsonb NOT NULL,
	"expires_at" timestamp,
	CONSTRAINT "cache_key_idx" UNIQUE("key")
);
--> statement-breakpoint
CREATE INDEX "cache_expires_at_idx" ON "cache" USING btree ("expires_at");