CREATE TABLE "issue_groups" (
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL,
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "issue_groups_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"title" text NOT NULL,
	"description" text,
	"embedding" vector(1536)
);
--> statement-breakpoint
ALTER TABLE "issue_groups" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "conversations_conversation" ADD COLUMN "issue_group_id" bigint;--> statement-breakpoint
ALTER TABLE "user_profiles" ADD COLUMN "pinned_issue_group_ids" jsonb DEFAULT '[]'::jsonb;--> statement-breakpoint
CREATE INDEX "issue_groups_created_at_idx" ON "issue_groups" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "issue_groups_embedding_idx" ON "issue_groups" USING hnsw ("embedding" vector_cosine_ops);--> statement-breakpoint
CREATE INDEX "conversations_issue_group_id_idx" ON "conversations_conversation" USING btree ("issue_group_id");