CREATE TABLE "tool_caches" (
  "created_at" timestamp with time zone NOT NULL,
  "updated_at" timestamp with time zone NOT NULL,
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "mailbox_id" bigint NOT NULL,
  "platform_customer_id" bigint,
  "tools" jsonb NOT NULL
);
--> statement-breakpoint
ALTER TABLE "tool_caches" ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
CREATE UNIQUE INDEX "tool_caches_mailbox_customer_idx" ON "tool_caches" ("mailbox_id","platform_customer_id");
