DROP TABLE "docs_embedding";--> statement-breakpoint
DROP TABLE "account_emailconfirmation";--> statement-breakpoint
DROP TABLE "account_emailaddress";--> statement-breakpoint
DROP TABLE "auth_user_user_permissions";--> statement-breakpoint
DROP TABLE "auth_group_permissions";--> statement-breakpoint
DROP TABLE "auth_permission";--> statement-breakpoint
DROP TABLE "auth_user_groups";--> statement-breakpoint
DROP TABLE "auth_group";--> statement-breakpoint
DROP TABLE "conversations_reply_bk";--> statement-breakpoint
DROP TABLE "django_admin_log";--> statement-breakpoint
DROP TABLE "django_content_type";--> statement-breakpoint
DROP TABLE "django_migrations";--> statement-breakpoint
DROP TABLE "django_session";--> statement-breakpoint
DROP TABLE "docs_article";--> statement-breakpoint
DROP TABLE "docs_category";--> statement-breakpoint
DROP TABLE "mailboxes_gumroaduser";--> statement-breakpoint
DROP TABLE "mailboxes_waitlistemail";--> statement-breakpoint
DROP TABLE "socialaccount_socialapp_sites";--> statement-breakpoint
DROP TABLE "socialaccount_socialtoken";--> statement-breakpoint
DROP TABLE "socialaccount_socialapp";--> statement-breakpoint
DROP TABLE "socialaccount_socialaccount";--> statement-breakpoint
DROP TABLE "django_site";--> statement-breakpoint
