CREATE TABLE IF NOT EXISTS "message_notifications" (
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL,
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "message_notifications_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"message_id" bigint NOT NULL,
	"conversation_id" bigint NOT NULL,
	"platform_customer_id" bigint NOT NULL,
	"status" text DEFAULT 'pending' NOT NULL,
	"notification_text" text,
	"sent_at" timestamp with time zone,
	"read_at" timestamp with time zone
);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "message_notifications_message_id_idx" ON "message_notifications" USING btree ("message_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "message_notifications_conversation_id_idx" ON "message_notifications" USING btree ("conversation_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "message_notifications_platform_customer_id_idx" ON "message_notifications" USING btree ("platform_customer_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "message_notifications_status_idx" ON "message_notifications" USING btree ("status");
