CREATE TABLE "conversations_topics" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "conversations_topics_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"conversation_id" bigint NOT NULL,
	"topic_id" bigint NOT NULL,
	"sub_topic_id" bigint,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"mailbox_id" bigint NOT NULL
);
--> statement-breakpoint
CREATE TABLE "topics" (
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL,
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "topics_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"custom_name" text,
	"parent_id" bigint,
	"mailbox_id" bigint
);
--> statement-breakpoint
CREATE INDEX "conversations_topics_conversation_id_idx" ON "conversations_topics" USING btree ("conversation_id");--> statement-breakpoint
CREATE INDEX "conversations_topics_topic_id_idx" ON "conversations_topics" USING btree ("topic_id");--> statement-breakpoint
CREATE INDEX "conversations_topics_sub_topic_id_idx" ON "conversations_topics" USING btree ("sub_topic_id");--> statement-breakpoint
CREATE INDEX "conversations_topics_created_at_idx" ON "conversations_topics" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "conversations_topics_mailbox_id_idx" ON "conversations_topics" USING btree ("mailbox_id");--> statement-breakpoint
CREATE INDEX "topics_parent_id_idx" ON "topics" USING btree ("parent_id");--> statement-breakpoint
CREATE INDEX "topics_mailbox_id_idx" ON "topics" USING btree ("mailbox_id");