CREATE TABLE "website_docs_crawls" (
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL,
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "website_docs_crawls_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"website_id" bigint NOT NULL,
	"name" varchar(255) NOT NULL,
	"status" varchar(50) NOT NULL,
	"metadata" jsonb,
	"error_message" text,
	"started_at" timestamp with time zone NOT NULL,
	"completed_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "website_docs_pages" (
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL,
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "website_docs_pages_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"website_id" bigint NOT NULL,
	"website_crawl_id" bigint NOT NULL,
	"url" text NOT NULL,
	"raw_html" text NOT NULL,
	"markdown" text NOT NULL,
	"page_title" text NOT NULL,
	"metadata" jsonb,
	"embedding" vector(1536),
	"deleted_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "website_docs" (
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL,
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "website_docs_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"mailbox_id" bigint NOT NULL,
	"name" varchar(255) NOT NULL,
	"url" text NOT NULL,
	"deleted_at" timestamp with time zone
);
--> statement-breakpoint
CREATE INDEX "website_crawls_created_at_idx" ON "website_docs_crawls" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "website_crawls_website_id_idx" ON "website_docs_crawls" USING btree ("website_id");--> statement-breakpoint
CREATE INDEX "website_crawls_status_idx" ON "website_docs_crawls" USING btree ("status");--> statement-breakpoint
CREATE INDEX "website_pages_created_at_idx" ON "website_docs_pages" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "website_pages_website_id_idx" ON "website_docs_pages" USING btree ("website_id");--> statement-breakpoint
CREATE INDEX "website_pages_website_crawl_id_idx" ON "website_docs_pages" USING btree ("website_crawl_id");--> statement-breakpoint
CREATE INDEX "website_pages_url_idx" ON "website_docs_pages" USING btree ("url");--> statement-breakpoint
CREATE INDEX "website_pages_embedding_index" ON "website_docs_pages" USING hnsw ("embedding" vector_cosine_ops);--> statement-breakpoint
CREATE INDEX "websites_created_at_idx" ON "website_docs" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "websites_mailbox_id_idx" ON "website_docs" USING btree ("mailbox_id");--> statement-breakpoint
CREATE INDEX "websites_url_idx" ON "website_docs" USING btree ("url");--> statement-breakpoint
